name: Suggerisco canti liturgici domenicali

on:
#  push:
  repository_dispatch:
  schedule:
    - cron:  '0 0 * * 1'
  workflow_dispatch:

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Utilizza l'action github checkout@v2, per automatizzare il check-out
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Enviroment setup (mlr, scrape, yq, scikit-learn, pandas)
      run: |-
        mkdir -p ~/bin
        cp bin/mlr ~/bin
        cp bin/scrape ~/bin
        cd ~/bin
        chmod +x mlr
        chmo +x sdcrape
        sudo pip install yq scikit-learn pandas
    - name: Suggerisci i canti della prossima domenica
      run: |-
        export PATH=$PATH:~/bin
        chmod +x ./build
        ./build
    - name: Committa e pusha se ci sono variazioni nei dati
      run: |-
        git config user.name "suggeritore-automatico"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date --iso-8601=seconds)
        git commit -m "Aggiornati i dati della prossima domenica ${timestamp}" || exit 0
        git push